spring:
  config:
    activate:
      on-profile:
        - local
  zipkin:
    base-url: http://localhost:9411/
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
