spring:
  config:
    activate:
      on-profile:
        - prod
  zipkin:
    base-url: http://host.docker.internal:9411/
    enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka
