server:
  port: 9001

spring:
  application:
    name: UserManagementService
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./UserManagementServiceDb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
