spring:
  application:
    name: UserManagementService
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./UserManagementServiceDb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

server:
  port: 9001
